language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree

gemfile:
  - Gemfile
  - gemfiles/Rails_3_0.gemfile
  - gemfiles/Rails_3_1.gemfile
  - gemfiles/Rails_3_2.gemfile

branches:
  only:
    - ruby18
